### ISSUE TITLE
Are you thinking about writing a Linux version?

### ISSUE THREAD

**Issue by shawndwells** [a0rtega/pafish#53]
Hi there. Have you considered writing a Linux version? I might be interested in helping you with that, then shipping it in EPEL. Has anyone else asked you about this before (couldn't find much on interwebs)?

**Comment by a0rtega** [comment]
Hi!

Well, as the project is focused on evasion tricks used by malware and most of it affects Windows, and also the analysis systems run Windows I think other operating systems are not as representative.

In addition I'm not really sure about the beneficts of shipping it in the repositories, as it's mostly intended to run in malware analysis systems.

I'm happy to hear proposals anyway, if we find a use case it'd be nice to work on it!

**Comment by preetd14** [comment]
Hi! I know this issue is closed but I think it would be very helpful for researchers since this is a hot topic in the security research community and recently there has been an uprising of malware in linux OSes as well. Since linux is the most preferred OS for production systems (i.e., servers and industrial machines), they tend to be the main target of a lot of attack groups. I think porting this project on linux would be very beneficial.

P.S. Is wine the only way of running this project on linux?
