### ISSUE TITLE
Delays within virtualization checks

### ISSUE THREAD

**Issue by 33c0c3** [a0rtega/pafish#69]
I was just curious as for the reason to implement the delays within these two virtualization detection loops:
https://github.com/a0rtega/pafish/blob/master/pafish/cpu.c#L89
https://github.com/a0rtega/pafish/blob/master/pafish/cpu.c#L100

I haven't seen this explained in literature related to time-based detections on virtualization, and I don't see how sleeping within these loops would yield different results.

Perhaps it relates to implementing this detection in usermode?

**Comment by a0rtega** [comment]
I added those sleeps in the loops because during my testing, some iterations of the loop returned an abnormally high difference in the TSC difference. I'm not sure what caused this, possibly CPU load peaks. The sleeps give pafish the chance to read the TSC at more separate moments in time, resulting in more neutral results. This is also the reason for calculating the average of ten iterations (calls), instead of just one call to the TSC reading function.
